name: "espressif idf build"
description: "This action build your firmware directly in github using Espressif idf SDK."
branding:
  color: blue
  icon: check
inputs:
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: ''
  idfVersion:
    description: 'ESP-IDF version tag of Docker image. E.g. latest, v4.2.1, release-v4.3'
    default: 'latest'
runs:
  using: "docker"
  image: 'docker://espressif/idf:${{ inputs.idfVersion }}'
  entrypoint: 'entrypoint.sh'
  args:
    - ${{ inputs.path }}
