name: "ESP-IDF build"
description: "This action build your firmware for ESP32 directly in GitHub using Espressif ESP-IDF."
branding:
  color: blue
  icon: check
inputs:
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
