name: "espressif idf build"
description: "This action build your firmware directly in github using Espressif idf SDK."
branding:
  color: blue
  icon: check
inputs:
  makearg:
    description: "Arguments to pass for make"
    required: false
    default: "defconfig all size-components"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.makearg }}
